// Downloads the deck's webfonts into fonts/ so the slides render with no network
// access at all. Re-run with `npm run fonts` after changing the `fonts:` block in
// slides.md; keep the two in sync (slides.md sets `provider: none`, which stops
// Slidev from injecting the Google Fonts <link>).
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

// Matches the `fonts:` headmatter in slides.md. Variable families take a weight
// range (one file per style); static ones need each weight listed separately.
const FAMILIES = [
  'IBM Plex Sans:ital,wght@0,300..700;1,300..700',
  'IBM Plex Mono:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700',
  'Newsreader:ital,opsz,wght@0,6..72,300..700;1,6..72,300..700',
]

// The deck is English; the other subsets Google serves are dead weight.
const SUBSETS = new Set(['latin', 'latin-ext'])

// Google returns woff2 only to browsers that advertise support.
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'

const outDir = resolve(dirname(fileURLToPath(import.meta.url)), '../fonts')

const slug = s => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')

async function main() {
  const url = `https://fonts.googleapis.com/css2?${FAMILIES.map(f => `family=${encodeURIComponent(f).replace(/%20/g, '+').replace(/%3A/g, ':').replace(/%40/g, '@').replace(/%3B/g, ';').replace(/%2C/g, ',')}`).join('&')}&display=swap`

  const res = await fetch(url, { headers: { 'User-Agent': UA } })
  if (!res.ok)
    throw new Error(`Google Fonts returned ${res.status} for ${url}`)
  const css = await res.text()

  await mkdir(outDir, { recursive: true })

  const blocks = [...css.matchAll(/\/\* (\S+) \*\/\s*(@font-face \{[^}]*\})/g)]
  if (!blocks.length)
    throw new Error('No @font-face blocks found; the css2 response format may have changed')

  const out = []
  let downloaded = 0

  for (const [, subset, block] of blocks) {
    if (!SUBSETS.has(subset))
      continue

    const family = /font-family: '([^']+)'/.exec(block)[1]
    const style = /font-style: (\S+);/.exec(block)[1]
    const weight = /font-weight: ([^;]+);/.exec(block)[1]
    const remote = /url\((https:[^)]+)\)/.exec(block)[1]

    const name = `${slug(family)}-${style}-${slug(weight)}-${subset}.woff2`
    const file = await fetch(remote)
    if (!file.ok)
      throw new Error(`Failed to download ${remote}: ${file.status}`)
    await writeFile(resolve(outDir, name), Buffer.from(await file.arrayBuffer()))
    downloaded++

    // Relative url() so Vite rewrites it and --base keeps working on Pages.
    out.push(block.replace(/url\(https:[^)]+\)/, `url('./${name}')`))
  }

  await writeFile(
    resolve(outDir, 'fonts.css'),
    `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n\n${out.join('\n\n')}\n`,
  )

  console.log(`Wrote ${downloaded} font files + fonts.css to fonts/`)
}

main()
